// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjoykgkdploqlizfhovm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqb3lrZ2tkcGxvcWxpemZob3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTY5NzMsImV4cCI6MjA2NjEzMjk3M30.Rskth_3g3w4sWEYHvcR313Sohe0_9Gr1on6rVHW41tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);